//
//  Currency.swift
//  budgeting-app
//
//  Created by Ivan Apostolovski on 3.11.24.
//

struct Currency: Identifiable, Hashable {
    let id: String
    let name: String
    let symbol: String
    let flag: String

    static let allCurrencies: [Currency] = [
        Currency(id: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸"),
        Currency(id: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺"),
        Currency(id: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧"),
        Currency(id: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵"),
        Currency(id: "AUD", name: "Australian Dollar", symbol: "$", flag: "🇦🇺"),
        Currency(id: "CAD", name: "Canadian Dollar", symbol: "$", flag: "🇨🇦"),
        Currency(id: "CHF", name: "Swiss Franc", symbol: "Fr", flag: "🇨🇭"),
        Currency(id: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳"),
        Currency(id: "MKD", name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰"),
        Currency(id: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳"),
        Currency(id: "NZD", name: "New Zealand Dollar", symbol: "$", flag: "🇳🇿"),
        Currency(id: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪"),
        Currency(id: "SGD", name: "Singapore Dollar", symbol: "$", flag: "🇸🇬"),
        Currency(id: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭"),
        Currency(id: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰"),
        Currency(id: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴"),
        Currency(id: "ILS", name: "Israeli Shekel", symbol: "₪", flag: "🇮🇱"),
        Currency(id: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦"),
        Currency(id: "HKD", name: "Hong Kong Dollar", symbol: "$", flag: "🇭🇰"),
        Currency(id: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷"),
        Currency(id: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷"),
        Currency(id: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺"),
        Currency(id: "PLN", name: "Polish Złoty", symbol: "zł", flag: "🇵🇱"),
        Currency(id: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷"),
        Currency(id: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽"),
        Currency(id: "AED", name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪"),
        Currency(id: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿"),
        Currency(id: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺"),
        Currency(id: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴"),
        Currency(id: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬"),
        Currency(id: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷"),
        Currency(id: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩"),
        Currency(id: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭"),
        Currency(id: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾"),
        Currency(id: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰"),
        Currency(id: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱"),
        Currency(id: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴"),
        Currency(id: "PEN", name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪"),
        Currency(id: "VND", name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳"),
        Currency(id: "EGP", name: "Egyptian Pound", symbol: "£", flag: "🇪🇬"),
        Currency(id: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷"),
        Currency(id: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶"),
        Currency(id: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", flag: "🇰🇼"),
        Currency(id: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", flag: "🇧🇭"),
        Currency(id: "OMR", name: "Omani Rial", symbol: "ر.ع.", flag: "🇴🇲"),
        Currency(id: "JOD", name: "Jordanian Dinar", symbol: "د.ا", flag: "🇯🇴"),
        Currency(id: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦"),
        Currency(id: "TND", name: "Tunisian Dinar", symbol: "د.ت", flag: "🇹🇳"),
        Currency(id: "LKR", name: "Sri Lankan Rupee", symbol: "රු", flag: "🇱🇰"),
        Currency(id: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩"),
        Currency(id: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬"),
        Currency(id: "GHS", name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭"),
        Currency(id: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪"),
        Currency(id: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿"),
        Currency(id: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬"),
        Currency(id: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲"),
        Currency(id: "SAR", name: "Saudi Riyal", symbol: "ر.س", flag: "🇸🇦"),
        Currency(id: "QAR", name: "Qatari Riyal", symbol: "ر.ق", flag: "🇶🇦"),
        Currency(id: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫"),
        Currency(id: "MNT", name: "Mongolian Tögrög", symbol: "₮", flag: "🇲🇳"),
        Currency(id: "XAF", name: "Central African CFA Franc", symbol: "FCFA", flag: "🇨🇲"),
        Currency(id: "XOF", name: "West African CFA Franc", symbol: "CFA", flag: "🇸🇳"),
        Currency(id: "XCD", name: "East Caribbean Dollar", symbol: "$", flag: "🇦🇬"),
        Currency(id: "JMD", name: "Jamaican Dollar", symbol: "$", flag: "🇯🇲"),
        Currency(id: "TTD", name: "Trinidad and Tobago Dollar", symbol: "$", flag: "🇹🇹"),
        Currency(id: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹"),
        Currency(id: "BSD", name: "Bahamian Dollar", symbol: "$", flag: "🇧🇸"),
        Currency(id: "BBD", name: "Barbadian Dollar", symbol: "$", flag: "🇧🇧"),
        Currency(id: "KYD", name: "Cayman Islands Dollar", symbol: "$", flag: "🇰🇾"),
        Currency(id: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", flag: "🇨🇼"),
        Currency(id: "AWG", name: "Aruban Florin", symbol: "ƒ", flag: "🇦🇼"),
        Currency(id: "NPR", name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵"),
        Currency(id: "MMK", name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲"),
        Currency(id: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿"),
        Currency(id: "UZS", name: "Uzbekistani Som", symbol: "so'm", flag: "🇺🇿"),
        Currency(id: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾"),
        Currency(id: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪"),
        Currency(id: "MDL", name: "Moldovan Leu", symbol: "L", flag: "🇲🇩"),
        Currency(id: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲"),
        Currency(id: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿"),
        Currency(id: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹"),
        Currency(id: "DZD", name: "Algerian Dinar", symbol: "دج", flag: "🇩🇿"),
        Currency(id: "LBP", name: "Lebanese Pound", symbol: "ل.ل", flag: "🇱🇧"),
        Currency(id: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪"),
        Currency(id: "SDG", name: "Sudanese Pound", symbol: "£", flag: "🇸🇩"),
        Currency(id: "SOS", name: "Somali Shilling", symbol: "Sh", flag: "🇸🇴"),
        Currency(id: "SCR", name: "Seychellois Rupee", symbol: "₨", flag: "🇸🇨"),
        Currency(id: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", flag: "🇲🇻"),
        Currency(id: "BZD", name: "Belize Dollar", symbol: "$", flag: "🇧🇿"),
        Currency(id: "SRD", name: "Surinamese Dollar", symbol: "$", flag: "🇸🇷"),
    ].sorted(by: { $0.name < $1.name })
}
